import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import './style.css';

const app=document.querySelector('#app');
app.innerHTML=`<div class="viewport" id="viewport"></div><header class="topbar"><div class="brand"><i class="mark"></i><span>ATLAS AMR</span></div><div class="tag">FULFILLMENT DIGITAL TWIN / WH-04</div><div class="controls"><button class="viewbtn" id="topView">TOP VIEW</button><button class="iconbtn" id="resetView">RESET</button></div><div class="online" id="connection">LIVE SYSTEM</div></header><section class="metrics" id="metrics"></section><aside class="side" id="detail"><div class="sidehead"><div class="robot-title"><i class="robot-symbol"></i><div><b>Robot inspector</b><small style="display:block">SELECT AN AMR</small></div></div></div><div class="sidebody"><div style="color:#718b8d;font-size:12px;padding:12px 0">Click any robot to inspect its real-time telemetry.</div></div></aside><div class="scale"><label>FLEET SCALE</label><select id="scale"><option>10</option><option selected>25</option><option>50</option><option>100</option></select></div><div class="hint">DRAG TO ORBIT · RIGHT-DRAG TO PAN · SCROLL TO ZOOM · CLICK ROBOT TO INSPECT</div><div class="toast" id="toast"></div>`;

const CELL=2.5,COLS=32,ROWS=20;
const world=(x,y)=>[(x-COLS/2)*CELL,(y-ROWS/2)*CELL];
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x071017); scene.fog=new THREE.FogExp2(0x071017,.009);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,300); camera.position.set(45,50,54);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; document.querySelector('#viewport').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.target.set(0,0,-1); controls.enableDamping=true; controls.dampingFactor=.07; controls.maxPolarAngle=Math.PI/2.05; controls.minDistance=18; controls.maxDistance=125;
scene.add(new THREE.HemisphereLight(0xb9e7e1,0x142126,1.8)); const sun=new THREE.DirectionalLight(0xe1fff7,2.4); sun.position.set(20,45,18); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;scene.add(sun);

function box(w,h,d,color,x,y,z,rough=.7){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.15}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
const floor=box(84,.5,54,0x26363a,0,-.35,0); floor.material.roughness=.9;
const grid=new THREE.GridHelper(80,32,0x416168,0x30484d);grid.position.y=-.08;grid.scale.z=.625;scene.add(grid);
// Safety perimeter and travel lanes.
const yellow=new THREE.MeshBasicMaterial({color:0xd7aa36,transparent:true,opacity:.75});
for(const z of [-22.5,22.5]){const l=new THREE.Mesh(new THREE.PlaneGeometry(78,.12),yellow);l.rotation.x=-Math.PI/2;l.position.set(0,-.065,z);scene.add(l)}
for(const y of [5,9,14]){const [,z]=world(0,y);const l=new THREE.Mesh(new THREE.PlaneGeometry(76,.07),new THREE.MeshBasicMaterial({color:0x5e8585,transparent:true,opacity:.42}));l.rotation.x=-Math.PI/2;l.position.set(0,-.06,z);scene.add(l)}
// Rack rows, inventory and aisle signs.
for(let x=5;x<27;x++){if(x%3===1)continue;for(let y=3;y<18;y++){if([5,9,14].includes(y))continue;const [wx,wz]=world(x,y);const rack=box(1.95,2.7,1.9,0x34464b,wx,1.35,wz);rack.material.metalness=.55; if((x+y)%3===0){const bin=box(1.45,.65,1.4,[0xd18c32,0x3a7f7a,0x678299][(x+y)%3],wx,1.55,wz);bin.userData.decor=true}}}
// Packing stations.
for(const y of [4,8,12,16]){const [x,z]=world(29,y);box(3.5,.7,2.2,0x46716e,x,.35,z);box(.16,2.7,.16,0x77918f,x-1.4,1.35,z);box(2.8,.08,.35,0x74dfbd,x,2.45,z-.8)}
// Charging docks and glowing pads.
for(let y=2;y<19;y+=2){const [x,z]=world(1,y);const dock=box(1.9,.15,1.9,0x16473d,x,-.02,z);dock.material.emissive=new THREE.Color(0x175f4e);dock.material.emissiveIntensity=.8;box(.28,1.1,1.9,0x2b3f42,x-1,.5,z)}
// Structural columns and ceiling light strips.
for(const x of [-39,39])for(const z of [-24,24])box(.45,7,.45,0x4c6265,x,3.5,z);

const robotGeo=new THREE.BoxGeometry(1.45,.52,1.7), robotMat=new THREE.MeshStandardMaterial({color:0xe39d2f,roughness:.42,metalness:.35});
const robotMeshes=new Map(), targets=new Map(); let latest=null,selected=null,follow=false;
function createRobot(r){const g=new THREE.Group();const body=new THREE.Mesh(robotGeo,robotMat.clone());body.position.y=.38;body.castShadow=true;g.add(body);const top=new THREE.Mesh(new THREE.BoxGeometry(1.18,.12,1.25),new THREE.MeshStandardMaterial({color:0x1d2c30,metalness:.7}));top.position.y=.7;g.add(top);const led=new THREE.Mesh(new THREE.SphereGeometry(.065,8,8),new THREE.MeshBasicMaterial({color:0x72f1c8}));led.position.set(.48,.8,.58);g.add(led);g.userData={robotId:r.id,body,cargo:null};scene.add(g);robotMeshes.set(r.id,g);return g}
function updateCargo(g,r){if(r.carrying&&!g.userData.cargo){const c=new THREE.Mesh(new THREE.BoxGeometry(1.15,.7,1.1),new THREE.MeshStandardMaterial({color:0x4a8d89,roughness:.7}));c.position.y=1.08;c.castShadow=true;g.add(c);g.userData.cargo=c}else if(!r.carrying&&g.userData.cargo){g.remove(g.userData.cargo);g.userData.cargo=null}}
function acceptState(data){latest=data;data.robots.forEach(r=>{const g=robotMeshes.get(r.id)||createRobot(r);targets.set(r.id,r);updateCargo(g,r)});for(const [id,g] of robotMeshes)if(!targets.has(id)){scene.remove(g);robotMeshes.delete(id)};renderMetrics(data.metrics);if(selected)renderDetail(data.robots.find(r=>r.id===selected))}
function renderMetrics(m){const t=new Date(m.simulationTime*1000).toISOString().slice(11,19);const vals=[['TOTAL ROBOTS',m.total,'units'],['ACTIVE',m.active,'moving'],['CHARGING',m.charging,'docked'],['WAITING',m.waiting,'traffic'],['DELIVERIES',m.completed,'completed'],['AVG BATTERY',m.averageBattery+'%','fleet'],['THROUGHPUT',m.throughput,'orders / hr'],['SIMULATION TIME',t,'12× realtime']];document.querySelector('#metrics').innerHTML=vals.map(v=>`<div class="metric"><span>${v[0]}</span><strong>${v[1]}</strong><em>${v[2]}</em></div>`).join('')}
function renderDetail(r){if(!r){selected=null;return}const battColor=r.battery<25?'#ef6d54':'#54dfb6';document.querySelector('#detail').innerHTML=`<div class="sidehead"><div class="robot-title"><i class="robot-symbol"></i><div><b>${r.id}</b><small style="display:block">${r.movement.toUpperCase()}</small></div></div><small>TELEMETRY</small></div><div class="sidebody"><div class="row"><span>Assignment</span><b>${r.task}</b></div><div class="row"><span>Battery</span><b>${r.battery}%</b></div><div class="batterybar"><i style="width:${r.battery}%;background:${battColor}"></i></div><div class="row"><span>Destination</span><b>${r.destination.x.toFixed(1)}, ${r.destination.z.toFixed(1)}</b></div><div class="row"><span>Current speed</span><b>${r.speed.toFixed(1)} m/s</b></div><div class="row"><span>Estimated arrival</span><b>${r.eta?Math.ceil(r.eta)+' sec':'Arrived'}</b></div><div class="row"><span>Cargo</span><b>${r.cargo||'No load'}</b></div><div class="row"><span>Reroutes</span><b>${r.reroutes}</b></div><button class="follow" id="follow">${follow?'STOP FOLLOWING':'FOLLOW ROBOT'}</button></div>`;document.querySelector('#follow').onclick=()=>{follow=!follow;renderDetail(r)}}
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;mouse.x=e.clientX/innerWidth*2-1;mouse.y=-(e.clientY/innerHeight)*2+1;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects([...robotMeshes.values()],true);if(hits.length){let o=hits[0].object;while(o.parent&&!o.userData.robotId)o=o.parent;if(o.userData.robotId){selected=o.userData.robotId;follow=false;renderDetail(targets.get(selected))}}});
function connect(){const proto=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${proto}://${location.host}/ws`);ws.onopen=()=>{document.querySelector('#connection').textContent='LIVE SYSTEM'};ws.onmessage=e=>acceptState(JSON.parse(e.data));ws.onclose=()=>{document.querySelector('#connection').textContent='RECONNECTING';setTimeout(connect,1500)};ws.onerror=()=>ws.close()}connect();
function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
document.querySelector('#scale').onchange=async e=>{const count=+e.target.value;const res=await fetch('/api/simulation/scale',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({robots:count})});if(res.ok){acceptState(await res.json());toast(`Fleet scaled to ${count} robots`)}}
document.querySelector('#topView').onclick=()=>{camera.position.set(0,94,.01);controls.target.set(0,0,0);controls.update()};document.querySelector('#resetView').onclick=()=>{follow=false;camera.position.set(45,50,54);controls.target.set(0,0,-1)};
function animate(){requestAnimationFrame(animate);for(const [id,g] of robotMeshes){const r=targets.get(id);if(!r)continue;g.position.x+=(r.x-g.position.x)*.17;g.position.z+=(r.z-g.position.z)*.17;let d=(r.rotation-g.rotation.y+Math.PI)%(Math.PI*2)-Math.PI;g.rotation.y+=d*.17;g.userData.body.material.color.setHex(r.charging?0x3cc09d:r.movement==='waiting'?0xd46f38:0xe39d2f)}if(follow&&selected){const g=robotMeshes.get(selected);if(g){const desired=g.position.clone().add(new THREE.Vector3(8,8,10));camera.position.lerp(desired,.04);controls.target.lerp(g.position,.12)}}controls.update();renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
